### ISSUE TITLE
c2 is not defined

### ISSUE THREAD

**Issue by DenisTimofijuk** [rollswan-acebedo/encrypter-js#1]
This tool currently is not possible to use.
```
encrypter-js.v1.0.0.js:42 Uncaught ReferenceError: c2 is not defined
    at Object.utf8Decode (encrypter-js.v1.0.0.js:42:45)
    at Object.decode (encrypter-js.v1.0.0.js:23:31)
    at Object.decrypt (encrypter-js.v1.0.0.js:67:24)
```

**Comment by rollswan-acebedo** [comment]
Hi @DenisTimofijuk I'd need more information.
but anyway, can you try again if error still appear. 
if does, do you mind to share your code. thank you

**Comment by DenisTimofijuk** [comment]
Just try to decode:
```
import rsBase64  from 'encrypter-js';
console.log( rsBase64.decrypt(rsBase64.encrypt("Hello World!")) )
```

It is able to encode, but it is not able to decode. When it tries to run decode it crashes on C2 variable.
I can not share all my code at the moment since there is a lot of stuff going on right now..
![Capture](https://user-images.githubusercontent.com/34959206/149168339-2a3e61e8-aef2-4cc6-a626-22ca57d0b880.JPG)
.

**Comment by rollswan-acebedo** [comment]
it seems to be working fine on my end.

<img width="752" alt="runkit encrypter-js" src="https://user-images.githubusercontent.com/62542042/149174271-18702661-30be-48ad-81e8-43b843e98a03.PNG">

**Comment by DenisTimofijuk** [comment]
If it helps, my code is now available on github:

https://github.com/DenisTimofijuk/game_find_6_diff/blob/main/src/1/1.ts

Please see commented code on lines  4 - 6

**Comment by rollswan-acebedo** [comment]
Hi @DenisTimofijuk  thanks for this.
try to update the package on your end.
I just release updates version 1.0.1. I hope it solve the problem. thank you

**Comment by DenisTimofijuk** [comment]
It works now. Thank you.

**Comment by rollswan-acebedo** [comment]
welcome. thank you for using the package
